apiVersion: batch/v1
kind: Job
metadata:
  name: niyyah-migrate
  namespace: niyyah
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: migrate
          image: gitlab-registry.homelab.alamin.rocks/niyyah/app/api:latest
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: niyyah-config
      restartPolicy: Never
  backoffLimit: 3
